import React from 'react'
import Head from 'next/head'
import { Layout } from '../components/Layout/MainLayout'
import HomeView from '../views/home'

export default function Home() {

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
    <HomeView />
      </Layout>
    </div>
  )
}
